<?php

/**
 * @file
 * Contains search_page.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function shop_page_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the shop_page module.
    case 'help.page.search_page':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Custom Search Page') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function search_page_theme() {
  return [
      'search_page' => [
          'render element' => 'children',
      ],
  ];
}