<?php

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;

function recently_viewed_products_theme ( $existing, $type, $theme, $path ) {
    return [
        'recently_viewed_products' => array(
            'template'  => 'recently_viewed_products',
            'variables' => [
                'content'  => [],
            ],
        ),

    ];
}

/**
 * Implements hook_ENTITY_TYPE_view() for node entities.
 */
function recently_viewed_products_node_view(array &$build, EntityInterface $node, EntityViewDisplayInterface $display, $view_mode) {
//    $_SESSION['recently_viewed'] = null;
    if($view_mode=='full' && $node->bundle() == 'furniture') {
        $id = $node->id();
        $_SESSION['recently_viewed'][$id] = time();

    }
}
