<?php

/**
 * @file
 * Contains furniture_list_page.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function furniture_list_page_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the search_page module.
    case 'help.page.furniture_list_page':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Custom Search Page') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function furniture_list_page_theme() {
  return [
      'furniture_list_page' => [
          'render element' => 'children',
      ],
  ];
}